sudo: false
language: cpp

compiler:
  - g++
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
    - liblua5.2-dev
    - libboost-all-dev
    - g++-5
    - gcc-5
    - cmake
env:
  - BUILD_TYPE=Release CXX_FLAGS=-std=c++14
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} && make
