sudo: false
language: cpp

compiler:
  - g++
before_install:
  - git submodule update --init --recursive
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - liblua5.2-dev
    - libboost-all-dev
    - g++-4.9
    - cmake
env:
  - BUILD_TYPE=Release
script:
  - mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} && make execute_benchmark

